import { createContext, useContext, useState, ReactNode } from "react";

type Language = "tr" | "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  tr: {
    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.about": "Hakkımızda", 
    "nav.services": "Hizmetlerimiz",
    "nav.projects": "Projelerimiz",
    "nav.contact": "İletişim",
    "nav.getQuote": "Teklif Al",

    // Hero Section
    "hero.badge": "20+ Yıllık Deneyim",
    "hero.title1": "Lojistikte Geleceği",
    "hero.title2": "Bir Proje ile İnşa Ediyoruz",
    "hero.subtitle": "Koçak Group, dünya standartlarında lojistik, ithalat-ihracat ve dış ticaret çözümleri sunarak kalite ve inovasyonda öncülük eder.",
    "hero.startProject": "Projenizi Başlatın",
    "hero.learnMore": "Daha Fazla Bilgi",
    "hero.stat1": "Proje",
    "hero.stat2": "Yıl",
    "hero.stat3": "Müşteri", 
    "hero.stat4": "Kalite",

    // About Section
    "about.title": "Koçak Group Hakkında",
    "about.subtitle": "Yirmi yılı aşkın süredir Koçak Group, lojistik, dış ticaret ve danışmanlık alanında öncü olarak güven inşa etmeye devam ediyor.",
    "about.story": "Hikayemiz",
    "about.story1": "2003 yılında kurulan Koçak Group, küçük bir lojistik şirketi olarak büyük bir vizyonla başladı: kaliteli hizmet ve yenilikçi çözümlerle ticareti dönüştürmek.",
    "about.story2": "Bugün, konut, ticari ve endüstriyel sektörlerde 500'den fazla projeyi başarıyla tamamlamış öncü bir lojistik ve dış ticaret grubu olarak duruyoruz.",
    "about.story3": "Geleneksel işçiliği modern teknoloji ile birleştirerek, her projenin en yüksek kalite, güvenlik ve sürdürülebilirlik standartlarını karşılamasını sağlıyoruz.",
    "about.completedProjects": "Tamamlanan Proje",
    "about.yearsExperience": "Yıllık Deneyim",
    "about.coreValues": "Temel Değerlerimiz",
    "about.excellence": "Mükemmellik",
    "about.excellenceDesc": "Her projede istisnai kalite sunarak, detaylara gösterilen titiz dikkatle müşteri beklentilerini aşıyoruz.",
    "about.innovation": "İnovasyon",
    "about.innovationDesc": "Yenilikçi çözümler sunmak için en son teknolojileri ve modern lojistik yöntemlerini benimseriz.",
    "about.reliability": "Güvenilirlik",
    "about.reliabilityDesc": "Geçmiş sicilimiz kendini kanıtlıyor - zamanında teslimat ve güvenebileceğiniz tutarlı kalite.",
    "about.sustainability": "Sürdürülebilirlik",
    "about.sustainabilityDesc": "Çevreye duyarlı lojistik uygulamalarını ve sürdürülebilir çözümleri öncelik olarak görüyoruz.",

    // Services
    "services.title": "Hizmetlerimiz",
    "services.subtitle": "Konseptten teslimata kadar, benzersiz proje gereksinimlerinizi karşılamak üzere uyarlanmış kapsamlı lojistik ve dış ticaret hizmetleri sunuyoruz.",
    "services.translation": "Tercümanlık ve Dil Hizmetleri",
    "services.translationDesc": "Yazılı-sözlü tercüme, yeminli tercüme, toplantı & fuar tercümanlığı",
    "services.importExport": "İthalat ve İhracat Danışmanlığı", 
    "services.importExportDesc": "Pazar araştırması, tedarikçi bulma, resmi belgeler hazırlama, dış ticaret desteği",
    "services.customs": "Gümrükleme Hizmetleri",
    "services.customsDesc": "İthalat & ihracat gümrük süreçlerinin yönetimi, evrak takibi",
    "services.logistics": "Uluslararası Lojistik ve Taşımacılık",
    "services.logisticsDesc": "Denizyolu, havayolu, karayolu taşımacılığı, parsiyel & komple yük",
    "services.storage": "Depolama ve Dağıtım Çözümleri", 
    "services.storageDesc": "Antrepo, geçici depolama, stok yönetimi, e-ticaret lojistiği",
    "services.consulting": "Danışmanlık ve Eğitim Hizmetleri",
    "services.consultingDesc": "Dış ticaret süreçleri, uluslararası ödeme yöntemleri, şirket kurulum danışmanlığı, eğitim & workshoplar",
    "services.learnMore": "Daha Fazla Bilgi →",
    "services.readyToStart": "Projenizi Başlatmaya Hazır mısınız?",
    "services.readyDesc": "Vizyonunuzu hayata geçirmek için nasıl yardımcı olabileceğimizi konuşalım.",
    "services.getConsultation": "Ücretsiz Danışmanlık Alın",

    // Projects
    "projects.title": "Projelerimiz",
    "projects.subtitle": "Çeşitli sektörlerde mükemmellik, inovasyon ve kaliteli işçilik konusundaki bağlılığımızı gösteren başarılı projeler portföyümüzü keşfedin.",
    "projects.all": "Tümü",
    "projects.logistics": "Lojistik",
    "projects.trade": "Dış Ticaret", 
    "projects.consulting": "Danışmanlık",
    "projects.translation": "Tercümanlık",
    "projects.viewDetails": "Detayları Görüntüle →",
    "projects.haveProject": "Aklınızda bir proje mi var? Vizyonunuzu hayata geçirelim.",
    "projects.startProject": "Projenizi Başlatın",

    // Why Choose Us
    "whyChoose.title": "Neden Koçak Group'u Seçmelisiniz?",
    "whyChoose.subtitle": "Lojistik ve dış ticaret sektöründe bizi farklı kılan özelliklerini keşfedin. Mükemmellik konusundaki bağlılığımız bizi yüzlerce memnun müşterinin tercih nedeni haline getirmiştir.",
    "whyChoose.provenTrack": "Kanıtlanmış Başarı",
    "whyChoose.provenDesc": "20 yılı aşkın başarılı proje teslimatı ile 500+ tamamlanmış proje ve memnun müşteri.",
    "whyChoose.quality": "Kaliteli İşçilik",
    "whyChoose.qualityDesc": "Her projede en yüksek kaliteyi sağlamak için premium malzemeler kullanır ve deneyimli uzmanlar istihdam ederiz.",
    "whyChoose.onTime": "Zamanında Teslimat",
    "whyChoose.onTimeDesc": "Son teslim tarihlerini yakalamak ve projeleri her zaman programda teslim etmekten gurur duyuyoruz.",
    "whyChoose.competitive": "Rekabetçi Fiyatlandırma",
    "whyChoose.competitiveDesc": "Kaliteden ödün vermeden rekabetçi fiyatlandırma sunarak yatırımınız için mükemmel değer sağlıyoruz.",
    "whyChoose.expert": "Uzman Takım",
    "whyChoose.expertDesc": "Deneyimli mühendis, mimar ve proje yöneticisi takımımız her projeye onlarca yıllık uzmanlık getiriyor.",
    "whyChoose.safety": "Güvenlik Öncelikli",
    "whyChoose.safetyDesc": "Tüm projelerimizde en yüksek güvenlik standartlarını koruyarak çalışan ve müşteri refahını sağlıyoruz.",
    "whyChoose.achievements": "Sayılarla Başarılarımız",
    "whyChoose.achievementsDesc": "Bu rakamlar mükemmellik ve müşteri memnuniyeti konusundaki bağlılığımızı yansıtıyor",
    "whyChoose.quote": "Koçak Group her açıdan beklentilerimizi aştı. Detaylara gösterdikleri dikkat, profesyonellik ve kalite konusundaki bağlılıkları lojistik projemizi tam bir başarı haline getirdi.",
    "whyChoose.quoteName": "Mehmet Yılmaz",
    "whyChoose.quoteTitle": "CEO, Yılmaz Holdings",
    "whyChoose.readyExperience": "Koçak Group Farkını Yaşamaya Hazır mısınız?",
    "whyChoose.joinClients": "En önemli projelerinde bize güvenen yüzlerce memnun müşteriye katılın.",
    "whyChoose.startToday": "Projenizi Bugün Başlatın",

    // Contact
    "contact.title": "İletişime Geçin",
    "contact.subtitle": "Bir sonraki projenizi başlatmaya hazır mısınız? Ücretsiz danışmanlık ve teklif için bugün bizimle iletişime geçin. Vizyonunuzu hayata geçirmek için ekibimiz burada.",
    "contact.sendMessage": "Bize Mesaj Gönderin",
    "contact.messageSent": "Mesaj Başarıyla Gönderildi!",
    "contact.thankYou": "Bizimle iletişime geçtiğiniz için teşekkürler. 24 saat içinde size geri dönüş yapacağız.",
    "contact.fullName": "Ad Soyad *",
    "contact.email": "E-posta Adresi *", 
    "contact.phone": "Telefon Numarası",
    "contact.projectType": "Proje Türü *",
    "contact.projectDetails": "Proje Detayları *",
    "contact.selectProject": "Proje türünü seçin",
    "contact.translation": "Tercümanlık Hizmetleri",
    "contact.importExport": "İthalat İhracat Danışmanlığı",
    "contact.customs": "Gümrükleme Hizmetleri", 
    "contact.logistics": "Lojistik ve Taşımacılık",
    "contact.storage": "Depolama Çözümleri",
    "contact.consulting": "Danışmanlık Hizmetleri",
    "contact.other": "Diğer",
    "contact.projectDetailsPlaceholder": "Proje gereksinimlerinizi, zaman çizelgenizi ve özel detayları lütfen açıklayın...",
    "contact.sendingMessage": "Mesaj Gönderiliyor...",
    "contact.sendMessageBtn": "Mesaj Gönder",
    "contact.address": "Adres", 
    "contact.workingHours": "Çalışma Saatleri",
    "contact.monFri": "Pzt - Cum: 08:00 - 18:00",
    "contact.saturday": "Cmt: 09:00 - 14:00",
    "contact.ourLocation": "Konumumuz",
    "contact.mapComing": "İnteraktif Harita Yakında",
    "contact.followUs": "Bizi Takip Edin",

    // Footer
    "footer.tagline": "Mükemmellik, inovasyon ve güvenilirlik ile geleceği inşa ediyoruz. 20 yılı aşkın süredir dünya standartlarında lojistik ve dış ticaret çözümleri sunuyoruz.",
    "footer.company": "Şirket",
    "footer.aboutUs": "Hakkımızda",
    "footer.ourStory": "Hikayemiz", 
    "footer.leadership": "Yönetim",
    "footer.careers": "Kariyer",
    "footer.services": "Hizmetler",
    "footer.translation": "Tercümanlık Hizmetleri",
    "footer.importExport": "İthalat İhracat",
    "footer.customs": "Gümrük İşlemleri",
    "footer.logistics": "Lojistik",
    "footer.projects": "Projeler",
    "footer.logisticsProjects": "Lojistik Projeler",
    "footer.tradeProjects": "Ticaret Projeleri",
    "footer.infrastructure": "Altyapı",
    "footer.industrial": "Endüstriyel",
    "footer.support": "Destek",
    "footer.contactUs": "İletişim",
    "footer.getQuote": "Teklif Al",
    "footer.supportCenter": "Destek Merkezi",
    "footer.faq": "S.S.S",
    "footer.stayUpdated": "Güncel Kalın",
    "footer.newsletter": "En son proje güncellemeleri ve lojistik içgörüleri için bültenimize abone olun.",
    "footer.enterEmail": "E-posta adresinizi girin",
    "footer.subscribe": "Abone Ol",
    "footer.rights": "© 2024 Koçak Group. Tüm hakları saklıdır.",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Şartları", 
    "footer.cookies": "Çerez Politikası",
    "footer.certified": "Sertifikalı & Lisanslı"
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services", 
    "nav.projects": "Projects",
    "nav.contact": "Contact",
    "nav.getQuote": "Get Quote",

    // Hero Section
    "hero.badge": "20+ Years of Excellence",
    "hero.title1": "Building the Future in Logistics,",
    "hero.title2": "One Project at a Time", 
    "hero.subtitle": "Koçak Group delivers world-class logistics, import-export and foreign trade solutions with unmatched quality and innovation.",
    "hero.startProject": "Start Your Project",
    "hero.learnMore": "Learn More",
    "hero.stat1": "Projects",
    "hero.stat2": "Years",
    "hero.stat3": "Clients",
    "hero.stat4": "Quality",

    // About Section
    "about.title": "About Koçak Group",
    "about.subtitle": "For over two decades, Koçak Group has been at the forefront of logistics, foreign trade and consulting, building trust through excellence and innovation.",
    "about.story": "Our Story",
    "about.story1": "Founded in 2003, Koçak Group began as a small logistics company with a big vision: to transform trade through quality service and innovative solutions.",
    "about.story2": "Today, we stand as a leading logistics and foreign trade group, having successfully completed over 500 projects across residential, commercial, and industrial sectors.",
    "about.story3": "We combine traditional craftsmanship with modern technology, ensuring every project meets the highest standards of quality, safety, and sustainability.",
    "about.completedProjects": "Completed Projects",
    "about.yearsExperience": "Years Experience",
    "about.coreValues": "Our Core Values",
    "about.excellence": "Excellence",
    "about.excellenceDesc": "We deliver exceptional quality in every project, exceeding client expectations through meticulous attention to detail.",
    "about.innovation": "Innovation",
    "about.innovationDesc": "We embrace cutting-edge technologies and modern logistics methods to deliver innovative solutions.",
    "about.reliability": "Reliability", 
    "about.reliabilityDesc": "Our track record speaks for itself - on-time delivery and consistent quality you can depend on.",
    "about.sustainability": "Sustainability",
    "about.sustainabilityDesc": "We prioritize environmentally conscious logistics practices and sustainable solutions.",

    // Services
    "services.title": "Our Services",
    "services.subtitle": "From concept to delivery, we offer comprehensive logistics and foreign trade services tailored to meet your unique project requirements.",
    "services.translation": "Translation and Language Services",
    "services.translationDesc": "Written-oral translation, sworn translation, meeting & fair interpretation",
    "services.importExport": "Import and Export Consulting",
    "services.importExportDesc": "Market research, supplier finding, official document preparation, foreign trade support",
    "services.customs": "Customs Services", 
    "services.customsDesc": "Management of import & export customs procedures, document tracking",
    "services.logistics": "International Logistics and Transportation",
    "services.logisticsDesc": "Sea, air, land transportation, partial & complete cargo",
    "services.storage": "Storage and Distribution Solutions",
    "services.storageDesc": "Warehouse, temporary storage, inventory management, e-commerce logistics",
    "services.consulting": "Consulting and Training Services",
    "services.consultingDesc": "Foreign trade processes, international payment methods, company establishment consulting, training & workshops",
    "services.learnMore": "Learn More →",
    "services.readyToStart": "Ready to Start Your Project?",
    "services.readyDesc": "Let's discuss how we can bring your vision to life.",
    "services.getConsultation": "Get Free Consultation",

    // Projects
    "projects.title": "Our Projects",
    "projects.subtitle": "Explore our portfolio of successful projects that showcase our commitment to excellence, innovation, and quality craftsmanship across various sectors.",
    "projects.all": "All",
    "projects.logistics": "Logistics",
    "projects.trade": "Foreign Trade",
    "projects.consulting": "Consulting", 
    "projects.translation": "Translation",
    "projects.viewDetails": "View Details →",
    "projects.haveProject": "Have a project in mind? Let's bring your vision to life.",
    "projects.startProject": "Start Your Project",

    // Why Choose Us
    "whyChoose.title": "Why Choose Koçak Group?",
    "whyChoose.subtitle": "Discover what sets us apart in the logistics and foreign trade industry. Our commitment to excellence has made us the preferred choice for hundreds of satisfied clients.",
    "whyChoose.provenTrack": "Proven Track Record",
    "whyChoose.provenDesc": "Over 20 years of successful project delivery with 500+ completed projects and satisfied clients.",
    "whyChoose.quality": "Quality Craftsmanship",
    "whyChoose.qualityDesc": "We use premium materials and employ skilled experts to ensure the highest quality in every project.",
    "whyChoose.onTime": "On-Time Delivery",
    "whyChoose.onTimeDesc": "We pride ourselves on meeting deadlines and delivering projects on schedule, every time.",
    "whyChoose.competitive": "Competitive Pricing",
    "whyChoose.competitiveDesc": "We offer competitive pricing without compromising on quality, providing excellent value for your investment.",
    "whyChoose.expert": "Expert Team",
    "whyChoose.expertDesc": "Our experienced team of engineers, architects, and project managers brings decades of expertise to every project.",
    "whyChoose.safety": "Safety First",
    "whyChoose.safetyDesc": "We maintain the highest safety standards on all our projects, ensuring the well-being of workers and clients.",
    "whyChoose.achievements": "Our Achievements by Numbers",
    "whyChoose.achievementsDesc": "These numbers reflect our commitment to excellence and client satisfaction",
    "whyChoose.quote": "Koçak Group exceeded our expectations in every way. Their attention to detail, professionalism, and commitment to quality made our logistics project a complete success.",
    "whyChoose.quoteName": "Mehmet Yılmaz", 
    "whyChoose.quoteTitle": "CEO, Yılmaz Holdings",
    "whyChoose.readyExperience": "Ready to Experience the Koçak Group Difference?",
    "whyChoose.joinClients": "Join hundreds of satisfied clients who have trusted us with their most important projects.",
    "whyChoose.startToday": "Start Your Project Today",

    // Contact
    "contact.title": "Get In Touch",
    "contact.subtitle": "Ready to start your next project? Contact us today for a free consultation and quote. Our team is here to help bring your vision to life.",
    "contact.sendMessage": "Send us a Message",
    "contact.messageSent": "Message Sent Successfully!",
    "contact.thankYou": "Thank you for contacting us. We'll get back to you within 24 hours.",
    "contact.fullName": "Full Name *",
    "contact.email": "Email Address *",
    "contact.phone": "Phone Number",
    "contact.projectType": "Project Type *",
    "contact.projectDetails": "Project Details *",
    "contact.selectProject": "Select project type",
    "contact.translation": "Translation Services",
    "contact.importExport": "Import Export Consulting",
    "contact.customs": "Customs Services",
    "contact.logistics": "Logistics & Transportation",
    "contact.storage": "Storage Solutions",
    "contact.consulting": "Consulting Services",
    "contact.other": "Other",
    "contact.projectDetailsPlaceholder": "Please describe your project requirements, timeline, and any specific details...",
    "contact.sendingMessage": "Sending Message...",
    "contact.sendMessageBtn": "Send Message",
    "contact.address": "Address",
    "contact.workingHours": "Working Hours",
    "contact.monFri": "Mon - Fri: 8:00 AM - 6:00 PM",
    "contact.saturday": "Sat: 9:00 AM - 2:00 PM",
    "contact.ourLocation": "Our Location",
    "contact.mapComing": "Interactive Map Coming Soon",
    "contact.followUs": "Follow Us",

    // Footer
    "footer.tagline": "Building the future with excellence, innovation, and reliability. For over 20 years, we've been delivering world-class logistics and foreign trade solutions.",
    "footer.company": "Company",
    "footer.aboutUs": "About Us",
    "footer.ourStory": "Our Story",
    "footer.leadership": "Leadership",
    "footer.careers": "Careers",
    "footer.services": "Services",
    "footer.translation": "Translation Services",
    "footer.importExport": "Import Export",
    "footer.customs": "Customs",
    "footer.logistics": "Logistics",
    "footer.projects": "Projects",
    "footer.logisticsProjects": "Logistics Projects",
    "footer.tradeProjects": "Trade Projects", 
    "footer.infrastructure": "Infrastructure",
    "footer.industrial": "Industrial",
    "footer.support": "Support",
    "footer.contactUs": "Contact Us",
    "footer.getQuote": "Get Quote",
    "footer.supportCenter": "Support Center",
    "footer.faq": "FAQ",
    "footer.stayUpdated": "Stay Updated",
    "footer.newsletter": "Subscribe to our newsletter for the latest project updates and logistics insights.",
    "footer.enterEmail": "Enter your email",
    "footer.subscribe": "Subscribe",
    "footer.rights": "© 2024 Koçak Group. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    "footer.certified": "Certified & Licensed"
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.projects": "مشاريعنا",
    "nav.contact": "اتصل بنا",
    "nav.getQuote": "احصل على عرض أسعار",

    // Hero Section
    "hero.badge": "+20 عامًا من التميز",
    "hero.title1": "بناء مستقبل اللوجستيات،",
    "hero.title2": "مشروع واحد في كل مرة",
    "hero.subtitle": "تقدم مجموعة كوتشاك حلول لوجستية وتجارة خارجية عالمية المستوى بجودة وابتكار لا مثيل لهما.",
    "hero.startProject": "ابدأ مشروعك",
    "hero.learnMore": "اعرف المزيد",
    "hero.stat1": "مشروع",
    "hero.stat2": "عامًا",
    "hero.stat3": "عميل",
    "hero.stat4": "جودة",

    // About Section
    "about.title": "حول مجموعة كوتشاك",
    "about.subtitle": "لأكثر من عقدين، كانت مجموعة كوتشاك في المقدمة في مجال اللوجستيات والتجارة الخارجية والاستشارات، بناء الثقة من خلال التميز والابتكار.",
    "about.story": "قصتنا",
    "about.story1": "تأسست في عام 2003، بدأت مجموعة كوتشاك كشركة لوجستيات صغيرة برؤية كبيرة: تحويل التجارة من خلال الخدمة عالية الجودة والحلول المبتكرة.",
    "about.story2": "اليوم، نقف كمجموعة لوجستية وتجارة خارجية رائدة، بعد إنجاز أكثر من 500 مشروع بنجاح عبر القطاعات السكنية والتجارية والصناعية.",
    "about.story3": "نجمع بين الحرفية التقليدية والتكنولوجيا الحديثة، مما يضمن أن كل مشروع يلبي أعلى معايير الجودة والسلامة والاستدامة.",
    "about.completedProjects": "مشروع مكتمل",
    "about.yearsExperience": "سنة خبرة",
    "about.coreValues": "قيمنا الأساسية",
    "about.excellence": "التميز",
    "about.excellenceDesc": "نقدم جودة استثنائية في كل مشروع، متجاوزين توقعات العملاء من خلال الاهتمام الدقيق بالتفاصيل.",
    "about.innovation": "الابتكار",
    "about.innovationDesc": "نحتضن التقنيات المتطورة وطرق اللوجستيات الحديثة لتقديم حلول مبتكرة.",
    "about.reliability": "الموثوقية",
    "about.reliabilityDesc": "سجلنا يتحدث عن نفسه - التسليم في الوقت المحدد والجودة المتسقة التي يمكنك الاعتماد عليها.",
    "about.sustainability": "الاستدامة",
    "about.sustainabilityDesc": "نعطي الأولوية للممارسات اللوجستية الصديقة للبيئة والحلول المستدامة.",

    // Services
    "services.title": "خدماتنا",
    "services.subtitle": "من المفهوم إلى التسليم، نقدم خدمات لوجستية وتجارة خارجية شاملة مصممة لتلبية متطلبات مشروعك الفريدة.",
    "services.translation": "خدمات الترجمة واللغة",
    "services.translationDesc": "الترجمة المكتوبة والشفوية، الترجمة المحلفة، ترجمة الاجتماعات والمعارض",
    "services.importExport": "استشارات الاستيراد والتصدير",
    "services.importExportDesc": "بحث ا��سوق، إيجاد الموردين، إعداد الوثائق الرسمية، دعم التجارة الخارجية",
    "services.customs": "خدمات الجمارك",
    "services.customsDesc": "إدارة إجراءات الجمارك للاستيراد والتصدير، تتبع الوثائق",
    "services.logistics": "اللوجستيات والنقل الدولي",
    "services.logisticsDesc": "النقل البحري، الجوي، البري، الشحن الجزئي والكامل",
    "services.storage": "حلول التخزين والتوزيع",
    "services.storageDesc": "المستودع، التخزين المؤقت، إدارة المخزون، لوجستيات التجارة الإلكترونية",
    "services.consulting": "خدمات الاستشارات والتدريب",
    "services.consultingDesc": "عمليات التجارة الخارجية، طرق الدفع الدولية، استشارات تأسيس الشركات، التدريب وورش العمل",
    "services.learnMore": "اعرف المزيد ←",
    "services.readyToStart": "هل أنت مستعد لبدء مشروعك؟",
    "services.readyDesc": "دعنا نناقش كيف يمكننا تحقيق رؤيتك.",
    "services.getConsultation": "احصل على استشارة مجانية",

    // Projects  
    "projects.title": "مشاريعنا",
    "projects.subtitle": "استكشف محفظة مشاريعنا الناجحة التي تظهر التزامنا بالتميز والابتكار والحرفية عالية الجودة عبر قطاعات متنوعة.",
    "projects.all": "الكل",
    "projects.logistics": "اللوجستيات",
    "projects.trade": "التجارة الخارجية",
    "projects.consulting": "الاستشارات",
    "projects.translation": "الترجمة",
    "projects.viewDetails": "عرض التفاصيل ←",
    "projects.haveProject": "هل لديك مشروع في الاعتبار؟ دعنا نحقق رؤيتك.",
    "projects.startProject": "ابدأ مشروعك",

    // Why Choose Us
    "whyChoose.title": "لماذا تختار مجموعة كوتشاك؟",
    "whyChoose.subtitle": "اكتشف ما يميزنا في صناعة اللوجستيات والتجارة الخارجية. التزامنا بالتميز جعلنا الخيار المفضل لمئات العملاء الراضين.",
    "whyChoose.provenTrack": "سجل حافل مثبت",
    "whyChoose.provenDesc": "أكثر من 20 عامًا من تسليم المشاريع الناجحة مع أكثر من 500 مشروع مكتمل وعملاء راضين.",
    "whyChoose.quality": "حرفية عالية الجودة",
    "whyChoose.qualityDesc": "نستخدم مواد عالية الجودة ونوظف خبراء مهرة لضمان أعلى جودة في كل مشروع.",
    "whyChoose.onTime": "التسليم في الوقت المحدد",
    "whyChoose.onTimeDesc": "نفتخر بالوفاء بالمواعيد النهائية وتسليم المشاريع في الموعد المحدد، في كل مرة.",
    "whyChoose.competitive": "تسعير تنافسي",
    "whyChoose.competitiveDesc": "نقدم تسعيرًا تنافسيًا دون التنازل عن الجودة، مما يوفر قيمة ممتازة لاستثمارك.",
    "whyChoose.expert": "فريق خبير",
    "whyChoose.expertDesc": "فريقنا ذو الخبرة من المهندسين والمعماريين ومديري المشاريع يجلب عقود من الخبرة لكل مشروع.",
    "whyChoose.safety": "السلامة أولاً",
    "whyChoose.safetyDesc": "نحافظ على أعلى معايير السلامة في جميع مشاريعنا، مما يضمن رفاهية العمال والعملاء.",
    "whyChoose.achievements": "إنجازاتنا بالأرقام",
    "whyChoose.achievementsDesc": "هذه الأرقام تعكس التزامنا بالتميز ورضا العملاء",
    "whyChoose.quote": "مجموعة كوتشاك تجاوزت توقعاتنا من جميع النواحي. اهتمامهم بالتفاصيل والمهنية والالتزام بالجودة جعل مشروعنا اللوجستي نجاحًا كاملاً.",
    "whyChoose.quoteName": "محمد يلماز",
    "whyChoose.quoteTitle": "الرئيس التنفيذي، يلماز القابضة",
    "whyChoose.readyExperience": "هل أنت مستعد لتجربة الفرق في مجموعة كوتشاك؟",
    "whyChoose.joinClients": "انضم إلى مئات العملاء الراضين الذين وثقوا بنا في مشاريعهم الأكثر أهمية.",
    "whyChoose.startToday": "ابدأ مشروعك اليوم",

    // Contact
    "contact.title": "تواصل معنا",
    "contact.subtitle": "هل أنت مستعد لبدء مشروعك التالي؟ اتصل بنا اليوم للحصول على استشارة وعرض أسعار مجاني. فريقنا هنا لمساعدتك في تحقيق رؤيتك.",
    "contact.sendMessage": "أرسل لنا رسالة",
    "contact.messageSent": "تم إرسال الرسالة بنجاح!",
    "contact.thankYou": "شكرًا لك على التواصل معنا. سنعاود الاتصال بك خلال 24 ساعة.",
    "contact.fullName": "الاسم الكامل *",
    "contact.email": "عنوان البريد الإلكتروني *",
    "contact.phone": "رقم الهاتف",
    "contact.projectType": "نوع المشروع *",
    "contact.projectDetails": "تفاصيل المشروع *",
    "contact.selectProject": "اختر نوع المشروع",
    "contact.translation": "خدمات الترجمة",
    "contact.importExport": "استشارات الاستيراد والتصدير",
    "contact.customs": "خدمات الجمارك",
    "contact.logistics": "اللوجستيات والنقل",
    "contact.storage": "حلول التخزين",
    "contact.consulting": "خدمات الاستشارات",
    "contact.other": "أخرى",
    "contact.projectDetailsPlaceholder": "يرجى وصف متطلبات مشروعك والجدول الزمني وأي تفاصيل خاصة...",
    "contact.sendingMessage": "جاري إرسال الرسالة...",
    "contact.sendMessageBtn": "إرسال الرسالة",
    "contact.address": "العنوان",
    "contact.workingHours": "ساعات العمل",
    "contact.monFri": "الإثنين - الجمعة: 8:00 ص - 6:00 م",
    "contact.saturday": "السبت: 9:00 ص - 2:00 م",
    "contact.ourLocation": "موقعنا",
    "contact.mapComing": "الخريطة التفاعلية قريبًا",
    "contact.followUs": "تابعنا",

    // Footer
    "footer.tagline": "بناء المستقبل بالتميز والابتكار والموثوقية. لأكثر من 20 عامًا، نقدم حلول لوجستية وتجارة خارجية عالمية المستوى.",
    "footer.company": "الشركة",
    "footer.aboutUs": "من نحن",
    "footer.ourStory": "قصتنا",
    "footer.leadership": "القيادة",
    "footer.careers": "الوظائف",
    "footer.services": "الخدمات",
    "footer.translation": "خدمات الترجمة",
    "footer.importExport": "الاستيراد والتصدير",
    "footer.customs": "الجمارك",
    "footer.logistics": "اللوجستيات",
    "footer.projects": "المشاريع",
    "footer.logisticsProjects": "مشاريع لوجستية",
    "footer.tradeProjects": "مشاريع تجارية",
    "footer.infrastructure": "البنية التحتية",
    "footer.industrial": "صناعي",
    "footer.support": "الدعم",
    "footer.contactUs": "اتصل بنا",
    "footer.getQuote": "احصل على عرض أسعار",
    "footer.supportCenter": "مركز الدعم",
    "footer.faq": "الأسئلة الشائعة",
    "footer.stayUpdated": "ابق على اطلاع",
    "footer.newsletter": "اشترك في نشرتنا الإخبارية لآخر تحديثات المشاريع والرؤى اللوجستية.",
    "footer.enterEmail": "أدخل بريدك الإلكتروني",
    "footer.subscribe": "اشترك",
    "footer.rights": "© 2024 مجموعة كوتشاك. جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.cookies": "سياسة ملفات تعريف الارتباط",
    "footer.certified": "معتمد ومرخص"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("tr");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === "ar" ? "rtl" : "ltr"} dir={language === "ar" ? "rtl" : "ltr"}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}